"""other test models

Revision ID: 2751e28f84a2
Revises: a4741fe5ac3d
Create Date: 2025-08-02 21:54:54.850628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2751e28f84a2'
down_revision: Union[str, None] = 'a4741fe5ac3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lea_symbols_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(), server_default=sa.text("'0%%'"), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('color_blindness_tests', sa.Column('score', sa.Boolean(), nullable=True))
    op.drop_column('color_blindness_tests', 'is_color_blind')
    op.add_column('tumbling_e_tests', sa.Column('total_questions', sa.Integer(), nullable=False))
    op.add_column('tumbling_e_tests', sa.Column('correct_answers', sa.Integer(), nullable=False))
    op.add_column('tumbling_e_tests', sa.Column('score', sa.String(), server_default=sa.text("'0%%'"), nullable=False))
    op.drop_column('tumbling_e_tests', 'score_percentage')
    op.drop_column('tumbling_e_tests', 'correct_directions')
    op.drop_column('tumbling_e_tests', 'total_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tumbling_e_tests', sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tumbling_e_tests', sa.Column('correct_directions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tumbling_e_tests', sa.Column('score_percentage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tumbling_e_tests', 'score')
    op.drop_column('tumbling_e_tests', 'correct_answers')
    op.drop_column('tumbling_e_tests', 'total_questions')
    op.add_column('color_blindness_tests', sa.Column('is_color_blind', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('color_blindness_tests', 'score')
    op.drop_table('lea_symbols_tests')
    # ### end Alembic commands ###
